### ISSUE TITLE
Filesystem Clears after shutdown

### ISSUE THREAD

**Issue by LynxPopulus** [xing1357/SimpleOS#11]
The filesystem clears, restarting setup, as the setupdone file does not exist anymore.

**Comment by xing1357** [comment]
Are you running on QEMU?

**Comment by LynxPopulus** [comment]
I have run it on both QEMU and VirtualBox, but the filesystem resets every time, with 0 files inside the `RAMDISK`.

**Comment by LynxPopulus** [comment]
I had modified the kernel a little bit, but still with the original provided `.iso` file, or an unedited build, the `RAMDISK` still doesn't work.

**Comment by LynxPopulus** [comment]
Also, when I load QEMU, it shows this:
`WARNING: Image format was not specified for 'MyOS.iso' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.`

So this may be the problem, as it can't conduct write operations on block 0.

**Comment by xing1357** [comment]
Yeah, I am going to include an actual initrd soon. Probably a floppy or smth.

**Comment by LynxPopulus** [comment]
Ok, thanks!
